#!/usr/bin/env node

/**
 * Metadata dumped in the following format from `parseFile`:
 *
 * {
 *   format: {
 *     tagTypes: [ 'ID3v2.3' ],
 *     lossless: false,
 *     container: 'MPEG',
 *     codec: 'MP3',
 *     sampleRate: 44100,
 *     numberOfChannels: 2,
 *     bitrate: 160000,
 *     tool: 'LAME 3.96\u0000\u0000',
 *     codecProfile: 'CBR',
 *     numberOfSamples: 381312,
 *     duration: 8.646530612244899
 *   },
 *   native: undefined,
 *   quality: { warnings: [] },
 *   common: {
 *     track: { no: 1, of: null },
 *     disk: { no: null, of: null },
 *     title: 'Untitled',
 *     artists: [ 'ZZ Pot' ],
 *     artist: 'ZZ Pot',
 *     album: 'ZZ Pot I'
 *   }
 * }
 */

const fs = require('fs');
const path = require('path');
const musicMetadata = require('music-metadata');

const sluggerize = (string) => {
  const a = 'àáâäæãåāăąçćčđďèéêëēėęěğǵḧîïíīįìłḿñńǹňôöòóœøōõőṕŕřßśšşșťțûüùúūǘůűųẃẍÿýžźż·/_,:;';
  const b = 'aaaaaaaaaacccddeeeeeeeegghiiiiiilmnnnnoooooooooprrsssssttuuuuuuuuuwxyyzzz------';
  const p = new RegExp(a.split('').join('|'), 'g');

  return string.toString().toLowerCase()
    .replace(/\s+/g, '-') // Replace spaces with -
    .replace(p, (c) => b.charAt(a.indexOf(c))) // Replace special characters
    .replace(/&/g, '-and-') // Replace & with 'and'
    .replace(/[^\w-]+/g, '') // Remove all non-word characters
    .replace(/--+/g, '-') // Replace multiple - with single -
    .replace(/^-+/, '') // Trim - from start of text
    .replace(/-+$/, ''); // Trim - from end of text
};

const formatTrackData = (data, trackFilePath) => {
  const artistPath = trackFilePath.split('/').slice(0, 3).join('/');
  const albumPath = trackFilePath.split('/').slice(0, 4).join('/');

  return {
    trackFilePath,
    albumPath: `${albumPath}/`,
    artistPath: `${artistPath}/`,
    title: data.common.title,
    album: data.common.album,
    artist: data.common.artist,
    titleSlug: sluggerize(data.common.title),
    albumSlug: sluggerize(data.common.album),
    artistSlug: sluggerize(data.common.artist),
    extra: {
      sampleRate: data.format.sampleRate,
      bitrate: data.format.bitrate,
      codecProfile: data.format.codecProfile,
      duration: data.format.duration,
      trackNumber: data.common.track.no,
    },
  };
};

const findFiles = (dir, type = /\.[a-z0-9]$/i, fileList = []) => {
  const files = fs.readdirSync(dir);

  files.forEach((file) => {
    const filePath = path.join(dir, file);
    const fileStat = fs.lstatSync(filePath);

    if (fileStat.isDirectory() && !file.startsWith('_')) {
      findFiles(filePath, type, fileList);
    } else if (type.test(filePath)) {
      fileList.push(filePath);
    }
  });

  return fileList;
};

class ID3Scraper {
  constructor(audioDir) {
    this.audioDir = audioDir;
    this.audioFiles = findFiles(audioDir, /\.mp3$/i);

    this.data = {};

    this.saveFiles = {
      catalog: './public/catalog.json',
    };
  }

  getMetadata() {
    return Promise.all(
      this.audioFiles.map((file) => (
        musicMetadata.parseFile(file).then((data) => (
          formatTrackData(data, file)
        ))
      )),
    );
  }

  storeArtist(metadata) {
    const { artistPath, artistSlug, artist } = metadata;

    if (this.data[artistSlug]) { return; }

    this.data[artistSlug] = {
      name: artist,
      path: artistPath,
      albums: {},
    };
  }

  storeAlbum(metadata) {
    const {
      album,
      albumPath,
      albumSlug,
      artistSlug,
    } = metadata;

    if (this.data[artistSlug].albums[albumSlug]) { return; }

    this.data[artistSlug].albums[albumSlug] = {
      name: album,
      path: albumPath,
      art: findFiles(albumPath, /\.(jpe?g|gif|png)$/i),
      tracks: [],
    };
  }

  storeTrack(metadata) {
    const {
      title,
      extra,
      albumSlug,
      titleSlug,
      artistSlug,
      trackFilePath,
    } = metadata;

    this.data[artistSlug].albums[albumSlug].tracks = (
      (this.data[artistSlug].albums[albumSlug].tracks || [])
    );

    this.data[artistSlug].albums[albumSlug].tracks.push({
      extra,
      title,
      slug: titleSlug,
      filePath: trackFilePath,
    });
  }

  sortTracks(metadata) {
    const { artistSlug, albumSlug } = metadata;

    this.data[artistSlug].albums[albumSlug].tracks.sort((a, b) => (
      a.extra.trackNumber - b.extra.trackNumber
    ));
  }

  saveCatalogFile() {
    fs.writeFileSync(this.saveFiles.catalog, JSON.stringify(this.data));
  }

  perform() {
    this.getMetadata().then((data) => {
      data.forEach((metadata) => {
        this.storeArtist(metadata);
        this.storeAlbum(metadata);
        this.storeTrack(metadata);
        this.sortTracks(metadata);
      });

      this.saveCatalogFile();
    });
  }
}

(new ID3Scraper('./public/audio/')).perform();
